### ISSUE TITLE
Doesn't work right when font size is large.

### ISSUE THREAD

**Issue by xelnaga64** [jrathlev/SynEdit-Spell-Checker#1]
First of all, this code is great, I appreciate your work.

I have an issue. If the font size is large, when I scroll to bottom lines, spell checker can't underline bad words. Is it possible to fix the issue?

**Comment by jrathlev** [comment]
Some more details would be helpful:
1. font size to provoke the issue
2. Windows screen resolution and selected text size 
3. steps to reproduce

**Comment by xelnaga64** [comment]
![1](https://user-images.githubusercontent.com/39432041/134778362-bbf2e6db-b7bb-4db5-98d1-ac7477d6ba67.png)
Works, perfectly well for font size 10 in demo.

![2](https://user-images.githubusercontent.com/39432041/134778401-86f64ee2-817b-46a2-ba56-d9b7bc82ddfd.png)
When I increase the font size, such as 28. The first page looks fine.

![3](https://user-images.githubusercontent.com/39432041/134778413-65f71c68-9252-4661-8cda-9f4fe0233b60.png)
When I scroll to bottom, it doesn't underline bad words.

My screen resolution is 1920x1080. Using Delphi 10.3.3 pro.

**Comment by jrathlev** [comment]
This issue is not related to the font size but to an enabled WordWrap property and was fixed in the current version of SynEditSpell.pas

**Comment by xelnaga64** [comment]
It solved the issue. THANK YOU VERY MUCH!!!
