### ISSUE TITLE
Not able to build x64 binary

### ISSUE THREAD

**Issue by xelnaga64** [jrathlev/SynEdit-Spell-Checker#2]
When I try to compile Win64, TSynEditSpellCheck.GetSuggestions function gives error.

This line: Inc(Integer(wrds),sizeOf(Pointer));

Error: [dcc64 Error] SynEditSpell.pas(675): E2064 Left side cannot be assigned to

**Comment by jrathlev** [comment]
The unit is designed to be used in 32 bit applications only.

**Comment by jrathlev** [comment]
The sources were updated to be compiled also for Win64

**Comment by xelnaga64** [comment]
THANK YOU! It works great!
