### ISSUE TITLE
Freezes after several "Find next misspelling" clicks. 

### ISSUE THREAD

**Issue by Dimon-II** [jrathlev/SynEdit-Spell-Checker#3]
The demo application gets stuck on the HTML and German tab.  
With the current version of Synedit, the **NextWordPosEx** function on _“non-English”_ words does not move to the next word and returns the same result, which leads to a freeze.

**Comment by jrathlev** [comment]
The provided unit SynEditSpell.pas was not up to date. Please check again.

**Comment by Dimon-II** [comment]
![image](https://github.com/jrathlev/SynEdit-Spell-Checker/assets/29166758/4bc269df-a166-4e70-bee7-c188c10b1668)
Error (freezes) present on SynEdit, installed via GetIt Package manager. You are using a different, older or forked version. There are no errors when installing your version.

**Comment by jrathlev** [comment]
I am using the files from the [SynEdit](https://github.com/SynEdit/SynEdit) Github repository.
